name = "workers-graphql-server"
type = "webpack"

account_id = ""
zone_id = ""
route = ""

workers_dev = true
webpack_config = "webpack.config.js"
compatibility_date = "2021-10-03"

# Enable a kv-namespace to use the KV caching feature
#
kv-namespaces = [
   { binding = "WORKERS_GRAPHQL_CACHE", id = "fbec75eb992c4795bf4db356d6f58b10" }
]

[build.upload]
format = "modules"
main = "./src/index.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"
